# Generated by Django 4.1 on 2022-08-12 14:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_rename_name_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 12, 14, 9, 33, 561377, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
