# Generated by Django 4.1 on 2022-08-12 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
