# Generated by Django 4.1 on 2022-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_lead_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(max_length=40),
        ),
    ]
